export const ADD_ROUTE = '/add'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const SEARCH_ROUTE = '/search'
export const PLACE_ROUTE = '/place'
